import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/store/provider";
import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider } from "@/contexts/sidebar-context";
import { SidebarWithContext } from "@/components/sidebar/sidebar";
import LazySidebarContent from "@/components/lazyLoad/lazyloadSidebarContent";
import { AuthProvider } from "@/contexts/auth-context";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} ${GeistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <AuthProvider>
              <TooltipProvider delayDuration={500} skipDelayDuration={500}>
                <SidebarProvider>
                  <SidebarWithContext>
                    <LazySidebarContent />
                  </SidebarWithContext>
                  <div className="h-dvh w-dvw overflow-hidden max-w-screen-2xl m-auto">
                    <Header />
                    {children}
                  </div>
                </SidebarProvider>
              </TooltipProvider>
            </AuthProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
